/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clasebanco;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
    }
    modelo cuentaDeBanco = new modelo();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        grupoTipoCuentas = new javax.swing.ButtonGroup();
        seccionCrearCuenta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        masculino = new javax.swing.JRadioButton();
        femenino = new javax.swing.JRadioButton();
        nombreCuenta = new javax.swing.JTextField();
        fechaCuenta = new javax.swing.JTextField();
        numeroTelefonoCuenta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        numeroCuenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ahorros = new javax.swing.JRadioButton();
        corriente = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        seccionOperaciones = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cuentaAUsar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fechaOperacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        valorOperacion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaConsignaciones = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaRetiros = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaSaldo = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi Banco");

        jLabel2.setText("Datos Personales");

        jLabel1.setText("Nombre");

        jLabel3.setText("Fecha de hoy");

        jLabel4.setText("Nro. de Telefono");

        jLabel5.setText("Sexo");

        grupoSexo.add(masculino);
        masculino.setText("Masculino");
        masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinoActionPerformed(evt);
            }
        });

        grupoSexo.add(femenino);
        femenino.setText("Femenino");
        femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femeninoActionPerformed(evt);
            }
        });

        nombreCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCuentaActionPerformed(evt);
            }
        });

        fechaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaCuentaActionPerformed(evt);
            }
        });

        jButton1.setText("Crear cuenta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Número de cuenta");

        jLabel7.setText("Tipo de cuenta");

        grupoTipoCuentas.add(ahorros);
        ahorros.setText("Ahorros");
        ahorros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ahorrosActionPerformed(evt);
            }
        });

        grupoTipoCuentas.add(corriente);
        corriente.setText("Corriente");
        corriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corrienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seccionCrearCuentaLayout = new javax.swing.GroupLayout(seccionCrearCuenta);
        seccionCrearCuenta.setLayout(seccionCrearCuentaLayout);
        seccionCrearCuentaLayout.setHorizontalGroup(
            seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionCrearCuentaLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jButton1)
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(seccionCrearCuentaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel2)
                        .addGroup(seccionCrearCuentaLayout.createSequentialGroup()
                            .addGroup(seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addGroup(seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGap(18, 18, 18)
                            .addGroup(seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(seccionCrearCuentaLayout.createSequentialGroup()
                                    .addGroup(seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel3)
                                        .addComponent(fechaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(33, 33, 33)
                                    .addGroup(seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(seccionCrearCuentaLayout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(54, 54, 54)
                                            .addComponent(jLabel5))
                                        .addGroup(seccionCrearCuentaLayout.createSequentialGroup()
                                            .addComponent(numeroTelefonoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(43, 43, 43)
                                            .addGroup(seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(femenino)
                                                .addComponent(masculino)))))
                                .addComponent(ahorros)
                                .addComponent(corriente))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        seccionCrearCuentaLayout.setVerticalGroup(
            seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionCrearCuentaLayout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(seccionCrearCuentaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(masculino)
                        .addComponent(nombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fechaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numeroTelefonoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(seccionCrearCuentaLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(femenino))
                        .addGroup(seccionCrearCuentaLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(seccionCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(numeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ahorros))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(corriente)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        jLabel8.setText("Número de cuenta");

        jLabel9.setText("Fecha");

        jLabel10.setText("Valor");

        jLabel11.setText("Tipo de operación");

        jButton2.setText("Consignar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Retirar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seccionOperacionesLayout = new javax.swing.GroupLayout(seccionOperaciones);
        seccionOperaciones.setLayout(seccionOperacionesLayout);
        seccionOperacionesLayout.setHorizontalGroup(
            seccionOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seccionOperacionesLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(seccionOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seccionOperacionesLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel11))
                    .addGroup(seccionOperacionesLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113))
            .addGroup(seccionOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(seccionOperacionesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(seccionOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cuentaAUsar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(76, 76, 76)
                    .addGroup(seccionOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fechaOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(81, 81, 81)
                    .addGroup(seccionOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(valorOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        seccionOperacionesLayout.setVerticalGroup(
            seccionOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seccionOperacionesLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addGroup(seccionOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
            .addGroup(seccionOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(seccionOperacionesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(seccionOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(seccionOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cuentaAUsar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fechaOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valorOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(62, Short.MAX_VALUE)))
        );

        areaConsignaciones.setColumns(20);
        areaConsignaciones.setRows(5);
        jScrollPane1.setViewportView(areaConsignaciones);

        areaRetiros.setColumns(20);
        areaRetiros.setRows(5);
        jScrollPane2.setViewportView(areaRetiros);

        jLabel12.setText("Consignaciones");

        jLabel13.setText("Retiros");

        areaSaldo.setColumns(20);
        areaSaldo.setRows(5);
        jScrollPane3.setViewportView(areaSaldo);

        jLabel14.setText("Saldo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(seccionCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(seccionOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel12)
                .addGap(136, 136, 136)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seccionCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seccionOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imprimirConsignaciones() {
        areaConsignaciones.append(fechaOperacion.getText()+" +"+ valorOperacion.getText()+"\n" );
    }
    private void imprimirSaldo(String fecha) {
        areaSaldo.append(fecha+ " = " +String.valueOf(cuentaDeBanco.getSaldo())+"\n");
    }
    private void imprimirRetiros() {
        areaRetiros.append(fechaOperacion.getText()+" -"+ valorOperacion.getText()+"\n" );
    }
    private void borrarTextos(javax.swing.JPanel panel) {
        
        for (int i = 0; i < panel.getComponentCount() ; i++) {
            javax.swing.JTextField campoABorrar;
            if (panel.getComponent(i) instanceof javax.swing.JTextField) { 
               campoABorrar = (javax.swing.JTextField) panel.getComponent(i);
               campoABorrar.setText(null);
            }
        }
    }
    private void nombreCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCuentaActionPerformed

    private void fechaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaCuentaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cuentaDeBanco.setNombre(nombreCuenta.getText());
        cuentaDeBanco.setFechaCreacion(fechaCuenta.getText());
        cuentaDeBanco.setNumeroTelefono(numeroTelefonoCuenta.getText());
        cuentaDeBanco.setSexo(grupoSexo.getSelection().getActionCommand());
        cuentaDeBanco.setNumeroDeCuenta(numeroCuenta.getText());
        cuentaDeBanco.setTipoDeCuenta(grupoTipoCuentas.getSelection().getActionCommand());
        cuentaDeBanco.setSaldo(0);
        imprimirSaldo(cuentaDeBanco.getFechaCreacion());
        borrarTextos(seccionCrearCuenta);
        grupoSexo.clearSelection();
        grupoTipoCuentas.clearSelection();
        JOptionPane.showMessageDialog(null, "Su cuenta ha sido creada correctamente");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinoActionPerformed
        // TODO add your handling code here:
        masculino.setActionCommand("Masculino");
    }//GEN-LAST:event_masculinoActionPerformed

    private void femeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femeninoActionPerformed
        // TODO add your handling code here:
        femenino.setActionCommand("Femenino");
    }//GEN-LAST:event_femeninoActionPerformed

    private void ahorrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ahorrosActionPerformed
        // TODO add your handling code here:
        ahorros.setActionCommand("Ahorros");
    }//GEN-LAST:event_ahorrosActionPerformed

    private void corrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corrienteActionPerformed
        // TODO add your handling code here:
        corriente.setActionCommand("Corriente");
    }//GEN-LAST:event_corrienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (cuentaDeBanco.getNumeroDeCuenta().equals(cuentaAUsar.getText())){
            cuentaDeBanco.setSaldo(Integer.parseInt(valorOperacion.getText()));
            imprimirConsignaciones();
            imprimirSaldo(fechaOperacion.getText());
            borrarTextos(seccionOperaciones);
        }
        else
            JOptionPane.showMessageDialog(null, "Introduzca un número de cuenta correcto");
        
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (cuentaDeBanco.getNumeroDeCuenta().equals(cuentaAUsar.getText()))
            if (cuentaDeBanco.getSaldo()>=Integer.parseInt(valorOperacion.getText())){
            cuentaDeBanco.setSaldo(Integer.parseInt(valorOperacion.getText())*-1);
            imprimirRetiros();
            imprimirSaldo(fechaOperacion.getText());
            borrarTextos(seccionOperaciones);
            }
            else
                JOptionPane.showMessageDialog(null, "No puede retirar un monto mayor a su saldo");
        else
            JOptionPane.showMessageDialog(null, "Introduzca un número de cuenta correcto");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ahorros;
    private javax.swing.JTextArea areaConsignaciones;
    private javax.swing.JTextArea areaRetiros;
    private javax.swing.JTextArea areaSaldo;
    private javax.swing.JRadioButton corriente;
    private javax.swing.JTextField cuentaAUsar;
    private javax.swing.JTextField fechaCuenta;
    private javax.swing.JTextField fechaOperacion;
    private javax.swing.JRadioButton femenino;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.ButtonGroup grupoTipoCuentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField nombreCuenta;
    private javax.swing.JTextField numeroCuenta;
    private javax.swing.JTextField numeroTelefonoCuenta;
    private javax.swing.JPanel seccionCrearCuenta;
    private javax.swing.JPanel seccionOperaciones;
    private javax.swing.JTextField valorOperacion;
    // End of variables declaration//GEN-END:variables
}
